CREATE TABLE `infusionsoft_contacts` (
  `Id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) DEFAULT NULL,
  `First Name` varchar(50) DEFAULT NULL,
  `Last Name` varchar(50) DEFAULT NULL,
  `Spouse Name` varchar(100) DEFAULT NULL,
  `Birthday` varchar(10) DEFAULT NULL,
  `Company Name` varchar(50) DEFAULT NULL,
  `Company Id` int(11) DEFAULT NULL,
  `Phone 1` varchar(30) DEFAULT NULL,
  `Phone 1 Ext` varchar(18) DEFAULT NULL,
  `Phone 1 Type` varchar(18) DEFAULT NULL,
  `Phone 2` varchar(30) DEFAULT NULL,
  `Phone 2 Ext` varchar(18) DEFAULT NULL,
  `Phone 2 Type` varchar(18) DEFAULT NULL,
  `Phone 3` varchar(30) DEFAULT NULL,
  `Phone 3 Ext` varchar(18) DEFAULT NULL,
  `Phone 3 Type` varchar(18) DEFAULT NULL,
  `Email` varchar(50) DEFAULT NULL,
  `Email Address 2` varchar(50) DEFAULT NULL,
  `Email Address 3` varchar(50) DEFAULT NULL,
  `Fax 1` varchar(18) DEFAULT NULL,
  `Fax 1 Type` varchar(18) DEFAULT NULL,
  `Fax 2` varchar(18) DEFAULT NULL,
  `Fax 2 Type` varchar(18) DEFAULT NULL,
  `Street Address 1` varchar(50) DEFAULT NULL,
  `Street Address 2` varchar(50) DEFAULT NULL,
  `City` varchar(50) DEFAULT NULL,
  `State` varchar(25) DEFAULT NULL,
  `Postal Code` varchar(10) DEFAULT NULL,
  `Zip Four` varchar(10) DEFAULT NULL,
  `Country` varchar(25) DEFAULT NULL,
  `Street Address 1 (Shipping)` varchar(50) DEFAULT NULL,
  `Street Address 2 (Shipping)` varchar(50) DEFAULT NULL,
  `City (Shipping)` varchar(10) DEFAULT NULL,
  `State (Shipping)` varchar(25) DEFAULT NULL,
  `Postal Code (Shipping)` varchar(10) DEFAULT NULL,
  `Zip Four (Shipping)` varchar(10) DEFAULT NULL,
  `Country (Shipping)` varchar(25) DEFAULT NULL,
  `Twitter` varchar(25) DEFAULT NULL,
  `Facebook` varchar(25) DEFAULT NULL,
  `LinkedIn` varchar(25) DEFAULT NULL,
  `Street Address 1 (Optional)` varchar(50) DEFAULT NULL,
  `Street Address 2 (Optional)` varchar(50) DEFAULT NULL,
  `City (Optional)` varchar(10) DEFAULT NULL,
  `State (Optional)` varchar(25) DEFAULT NULL,
  `Postal Code (Optional)` varchar(10) DEFAULT NULL,
  `Zip Four (Optional)` varchar(10) DEFAULT NULL,
  `Country (Optional)` varchar(10) DEFAULT NULL,
  `Phone 4` varchar(30) DEFAULT NULL,
  `Phone 4 Ext` varchar(18) DEFAULT NULL,
  `Phone 4 Type` varchar(18) DEFAULT NULL,
  `Phone 5` varchar(30) DEFAULT NULL,
  `Phone 5 Ext` varchar(18) DEFAULT NULL,
  `Phone 5 Type` varchar(18) DEFAULT NULL,
  `Tag Ids` varchar(100) DEFAULT NULL,
  `Tags` blob,
  `Person Type` varchar(10) DEFAULT NULL,
  `Job Title` varchar(50) DEFAULT NULL,
  `Website` varchar(25) DEFAULT NULL,
  `SSN` varchar(10) DEFAULT NULL,
  `Last 4 SSN` varchar(10) DEFAULT NULL,
  `Middle Name` varchar(15) DEFAULT NULL,
  `Nickname` varchar(25) DEFAULT NULL,
  `Username` varchar(25) DEFAULT NULL,
  `Password` varchar(10) DEFAULT NULL,
  `Assistant Name` varchar(50) DEFAULT NULL,
  `Assistant Phone` varchar(18) DEFAULT NULL,
  `Title` varchar(25) DEFAULT NULL,
  `Suffix` varchar(10) DEFAULT NULL,
  `Anniversary` varchar(10) DEFAULT NULL,
  `Created By` varchar(25) DEFAULT NULL,
  `Date Created` varchar(20) DEFAULT NULL,
  `Last Updated` varchar(20) DEFAULT NULL,
  `OwnerID` int(1) DEFAULT NULL,
  `Language` varchar(10) DEFAULT NULL,
  `Time Zone` varchar(10) DEFAULT NULL,
  `Owner` varchar(25) DEFAULT NULL,
  `Lead Source` varchar(15) DEFAULT NULL,
  `Lead Source Category` varchar(10) DEFAULT NULL,
  `Referral Code` varchar(10) DEFAULT NULL,
  `Add Method` varchar(25) DEFAULT NULL,
  `Date Added` varchar(20) DEFAULT NULL,
  `Dateof Last Followup` varchar(20) DEFAULT NULL,
  `Message` varchar(10) DEFAULT NULL,
  `Name 1` varchar(50) DEFAULT NULL,
  `Status` varchar(10) DEFAULT NULL,
  `Verified` varchar(10) DEFAULT NULL,
  `OraPassword` varchar(30) DEFAULT NULL,
  `Date Entered` varchar(20) DEFAULT NULL,
  `Latest IP` varchar(15) DEFAULT NULL,
  `Original IP` varchar(15) DEFAULT NULL,
  `Lead Score` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
