CREATE TABLE `infusionsoft_orders` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ContactId` int(11) DEFAULT NULL,
  `Contact` varchar(100) DEFAULT NULL,
  `First Name` varchar(50) DEFAULT NULL,
  `Last Name` varchar(50) DEFAULT NULL,
  `Title` varchar(15) DEFAULT NULL,
  `Co Name` varchar(50) DEFAULT NULL,
  `Street Address 1` varchar(150) DEFAULT NULL,
  `Street Address 2` varchar(150) DEFAULT NULL,
  `City` varchar(50) DEFAULT NULL,
  `State` varchar(6) DEFAULT NULL,
  `Postal Code` varchar(10) DEFAULT NULL,
  `Country` varchar(25) DEFAULT NULL,
  `Order Type` varchar(20) DEFAULT NULL,
  `Promo Code` varchar(20) DEFAULT NULL,
  `Order Title` varchar(50) DEFAULT NULL,
  `Order Date` varchar(20) DEFAULT NULL,
  `Order Date-datetime` date DEFAULT NULL,
  `Product Ids` varchar(25) DEFAULT NULL,
  `Product Name` blob,
  `Serial` varchar(20) DEFAULT NULL,
  `Order Total` varchar(10) DEFAULT NULL,
  `Order Total-float` float(6,2) DEFAULT NULL,
  `Affiliate Id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
